version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/python:2.7.15
    steps:
      - checkout

      - run: echo $SERVICE_ACCOUNT_JSON >> serviceAccount.json
      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pipenv run "py.test"

